spring:
  application:
    name: gateway
  cloud:
    gateway:
#      httpclient:
#        pool:
#          max-idle-time:
#          max-connections:
      discovery:
        locator:
          # 开启后默认通过服务名称可以路由到服务内部，但是通过此方法路由过去触发hystrix有问题，超时设置无效，建议关闭
          enabled: false
          lower-case-service-id: true
      # 服务路由设置
      routes:
      - id: auth-route
        uri: lb://auth
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: social-route
        uri: lb://social
        predicates:
        - Path=/api/social/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: notice-route
        uri: lb://notice
        predicates:
        - Path=/api/notice/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: pay-route
        uri: lb://pay
        predicates:
        - Path=/api/pay/**
        filters:
        - StripPrefix=2
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      # cors 全局设置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    circuitbreaker:
      hystrix:
        enabled: true
  profiles:
    # 使用测试配置
    active: local

# hystrix 超时设置
hystrix:
  command:
    fallbackcmd:
      execution:
#        timeout:
#          enable: true
        isolation:
#          strategy: SEMAPHORE
          strategy: THREAD
#          semaphore:
#            maxConcurrentRequests: 200
          thread:
            timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800


# actuator 暴露 hystrix
management:
  endpoints:
    web:
      exposure:
        include: info,hystrix.stream
      base-path: /actuator

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
