# 测试配置

server:
  port: 8088

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8001/eureka/
      defaultZone: http://101.34.163.168:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway