version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    ports:
      - 5601:5601
    volumes:
      - './certs:/usr/share/kibana/config/certs'
      - './kibana.yml:/usr/share/kibana/config/kibana.yml'
    networks:
      - es_default


networks:
  es_default:
    external: true

