# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: gtc-test-build

    steps:
    - uses: actions/checkout@master

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml -Dmaven.test.skip=true

    - name: Connet to server & Open docker transfer port
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        password: ${{ secrets.TEST_PASSWORD }}
        port: ${{ secrets.TEST_PORT }}
        script: |
          whoami
          cd /root
          ./open_port_2375.sh

    - name: Start to upload docker image
      run: |
        export DOCKER_HOST=tcp://${{ secrets.TEST_HOST }}:2375
        cd auth_service
        mvn docker:build
        cd ../social_service
        mvn docker:build

    - name: Connect to server & Close docker tranfer port & restart docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USERNAME }}
        password: ${{ secrets.TEST_PASSWORD }}
        port: ${{ secrets.TEST_PORT }}
        script: |
          whoami
          cd /root
          ./close_port_2375.sh
          docker stop gtc_auth
          docker rm gtc_auth
          sudo docker run -p 8002:8002 --name gtc_auth -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /root/docker/logs/auth/:/ROOT/logs/ -d auth
          docker stop gtc_social
          docker rm gtc_social
          sudo docker run -p 8003:8003 --name gtc_social -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -v /root/docker/logs/social/:/ROOT/logs/ -d social









